[ipify]
key = "at_nf074pgWFVHxose3BeTjPfF36TcyD"
url_country = "https://geo.ipify.org/api/v2/country"
url_ip = "https://api.ipify.org"

[ontv]
api_url = "http://127.0.0.1:7778/api"
leagues = [
  25,
  117,
  8,
  1,
  570,
  7,
  7752,
  11,
  15,
  13,
  35,
  37,
  163,
  5668,
  350,
  572,
  573,
  7016,
  6071,
  7685,
  5421,
  7685,
  5788,
  17,
  7742,
  133,
  332,
]

[threesixfive]
competitions_json = "competitions.json"
leagues_json = "leagues.json"

[favourites]
teams = [108, 131, 66796]

[music]
api_url = "http://127.0.0.1:5083/znayko"
storage = "/store/Misic"

[cachable]
path = "/Volumes/Devo/Code/znayko/cache"

[demographics]
faggots = [
  "boris johnson",
  "tim cummins",
  "borislav mihaylov",
  "bobi mihaylov",
  "parvez kazi",
  "bartosz trzcinski",
  "bart trzcinski",
  "Volodymyr Zelenskyy",
  "budimir",
]

[chatyo]
base_url = "http://192.168.0.107:23726"

[image]
base_url = "http://192.168.0.107:23726"

[geo]
base_url = "http://192.168.0.10:21234"

[api]
port = 31313

[beats]
db_url = "postgresql://127.0.0.1:5432/beats"

