
from botyo.cli import pass_environment, Environment
import click
from botyo.commands import coro
from botyo.firebase.service_account import ServiceAccount
import os
from botyo.firebase.firestore import FirestoreClient
from botyo.firebase.auth import Auth
from pathlib import Path
import logging

ServiceAccount.register(Path(os.environ.get("BOTYO_SERVICE_ACCOUNT", "")))


@click.command("firestore", short_help="firestore tests")
@pass_environment
@coro
def cli(ctx: Environment):
    print(Auth.verify('eyJhbGciOiJSUzI1NiIsImtpZCI6ImQwNWI0MDljNmYyMmM0MDNlMWY5MWY5ODY3YWM0OTJhOTA2MTk1NTgiLCJ0eXAiOiJKV1QifQ.eyJuYW1lIjoiQWxleGFuZGVyIFNwYXNzb3YiLCJwaWN0dXJlIjoiaHR0cHM6Ly9saDMuZ29vZ2xldXNlcmNvbnRlbnQuY29tL2EvQUVkRlRwNGdPb0wyTXZQS3k5ZE4wZG1leGxSWnNkSVRNclMyYktSQXNTdjZGQT1zOTYtYyIsImlzcyI6Imh0dHBzOi8vc2VjdXJldG9rZW4uZ29vZ2xlLmNvbS9ib3R5by02ZDNlNCIsImF1ZCI6ImJvdHlvLTZkM2U0IiwiYXV0aF90aW1lIjoxNjc1MjgwOTAyLCJ1c2VyX2lkIjoiSTQzWkFqVFRxQk1oNG1kSGM5U0NaOUlBYjUzMyIsInN1YiI6Ikk0M1pBalRUcUJNaDRtZEhjOVNDWjlJQWI1MzMiLCJpYXQiOjE2NzU0MzQ3MTQsImV4cCI6MTY3NTQzODMxNCwiZW1haWwiOiJzcGFzc292QGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7Imdvb2dsZS5jb20iOlsiMTA5NTYwNTAwOTYzOTkwNzcwMzU1Il0sImVtYWlsIjpbInNwYXNzb3ZAZ21haWwuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoiZ29vZ2xlLmNvbSJ9fQ.bPhtc53qno0BDURS2efRRo4SiqBpqgm1CiLgZ_ozhnL61NCWSrVJvTk4JFFu_papK-QtOJ49EYNA4O-wrtjbrxN8Oz7JGs7Q9SrJYX2WnEVFUQB2Xm42QohrtQNdQEY7yvkm4ks_Pz8w51a2WwrgKzE1Wabpjhoo9fskezcWpL7fPfq9QMztAUoDJwDudDQzXlRVjSS4QsBy--SeW-Zd6-OYnO8SVa02O0HKYImJoCKdV9nFF0y8yYXltt6e0TwbtKO6mZHnE4yYDd2c9NaoHTIdyrrfd5wZK630gY1JuZMTlEHsp7x8x4jpaEGy9PVfNLasQ1mafWW1eFj7OH2RJA'))
