
from botyo.cli import pass_environment, Environment
import click
from botyo.commands import coro
from botyo.firebase.service_account import ServiceAccount
import os
from botyo.firebase.firestore import FirestoreClient
from botyo.firebase.auth import Auth
from pathlib import Path
import logging

ServiceAccount.register(Path(os.environ.get("BOTYO_SERVICE_ACCOUNT", "")))


@click.command("firestore", short_help="firestore tests")
@pass_environment
@coro
def cli(ctx: Environment):
    print(Auth.verify('eyJhbGciOiJSUzI1NiIsImtpZCI6ImQwNWI0MDljNmYyMmM0MDNlMWY5MWY5ODY3YWM0OTJhOTA2MTk1NTgiLCJ0eXAiOiJKV1QifQ.eyJuYW1lIjoiQWxleGFuZGVyIFNwYXNzb3YiLCJwaWN0dXJlIjoiaHR0cHM6Ly9saDMuZ29vZ2xldXNlcmNvbnRlbnQuY29tL2EvQUVkRlRwNGdPb0wyTXZQS3k5ZE4wZG1leGxSWnNkSVRNclMyYktSQXNTdjZGQT1zOTYtYyIsImlzcyI6Imh0dHBzOi8vc2VjdXJldG9rZW4uZ29vZ2xlLmNvbS9ib3R5by02ZDNlNCIsImF1ZCI6ImJvdHlvLTZkM2U0IiwiYXV0aF90aW1lIjoxNjc1MjgwOTAyLCJ1c2VyX2lkIjoiSTQzWkFqVFRxQk1oNG1kSGM5U0NaOUlBYjUzMyIsInN1YiI6Ikk0M1pBalRUcUJNaDRtZEhjOVNDWjlJQWI1MzMiLCJpYXQiOjE2NzU0NDAxMTMsImV4cCI6MTY3NTQ0MzcxMywiZW1haWwiOiJzcGFzc292QGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7Imdvb2dsZS5jb20iOlsiMTA5NTYwNTAwOTYzOTkwNzcwMzU1Il0sImVtYWlsIjpbInNwYXNzb3ZAZ21haWwuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoiZ29vZ2xlLmNvbSJ9fQ.ADtaFblTMivqpwKnpRz4e0j6dYn3hNSWRmd10Yo3VwBI1VnVP1Lr8-HJB0EEzShLCSLwF0XTZa6_M0KYjlNqKn-TMfuN4SH8byuav6UJEimT3miR7YkDok7nR6az7fi91DvpqFYdNlW65yeDsVYDpSnNaVutAph40W9-ES2g6V8SbkWeedQbM1VJINxpObWV5b9u3FP-r9x4qSbxdO0RmCYrh5BUmRQaqUIg8ZG9kXly9jNtfvan4GdwBAu_djDTBzibrvCwlmbLQ1GajKE1uSjzUDxYy5Akpzw56uVXxZshcE0YoDaOURkfH3Cw-9lVO1JB5qXU1roADmjseDfR7Q'))